version: '3'

services:  
    localstack:
        image: localstack/localstack-light:0.11.2
        ports:
            - 4582:4582
            - 4569:4569
        environment:
            - SERVICES=cloudwatch,dynamodb
            - DEFAULT_REGION=us-east-1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
            - LAMBDA_EXECUTOR=docker
        volumes:
            - ./.localstack:/tmp/localstack
            - /var/run/docker.sock:/var/run/docker.sock